name: unit-tests
on:
  pull_request:
    branches: [main]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run Unit Tests
        run: yarn && yarn test
